Correct workflow file

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -86,19 +86,19 @@ jobs:
             docker compose up -d --build
             docker image prune -f
 
-notify:
-    name: Status Report
-    needs: [deploy]
-    if: always()
-    runs-on: ubuntu-latest
-    steps:
-      - name: Report Status
-        run: |
-          if [ "${{ needs.deploy.result }}" == "success" ]; then
-            echo "Codesdev Deployed Successfully!"
-          elif [ "${{ needs.deploy.result }}" == "skipped" ]; then
-            echo "CI Checks Passed. Deployment skipped (not on main branch)."
-          else
-            echo "Deployment Failed."
-            exit 1
-          fi
+  notify:
+      name: Status Report
+      needs: [deploy]
+      if: always()
+      runs-on: ubuntu-latest
+      steps:
+        - name: Report Status
+          run: |
+            if [ "${{ needs.deploy.result }}" == "success" ]; then
+              echo "Codesdev Deployed Successfully!"
+            elif [ "${{ needs.deploy.result }}" == "skipped" ]; then
+              echo "CI Checks Passed. Deployment skipped (not on main branch)."
+            else
+              echo "Deployment Failed."
+              exit 1
+            fi
